runtime: go111

handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /robots.txt
    static_files: robots.txt
    upload: robots.txt

  - url: /admin/.*
    script: auto
    secure: always
    login: admin

  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  max_concurrent_requests: 80
  max_instances: 1
