runtime: go
api_version: go1

handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /admin/.*
    script: _go_app
    secure: always
    login: admin

  - url: /.*
    script: _go_app
    secure: always
