// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// .google.type.Date: https://github.com/googleapis/googleapis/blob/master/google/type/date.proto
type Date struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year  *int32 `protobuf:"varint,1,opt,name=year" json:"year,omitempty"`
	Month *int32 `protobuf:"varint,2,opt,name=month" json:"month,omitempty"`
	Day   *int32 `protobuf:"varint,3,opt,name=day" json:"day,omitempty"`
}

func (x *Date) Reset() {
	*x = Date{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *Date) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *Date) GetMonth() int32 {
	if x != nil && x.Month != nil {
		return *x.Month
	}
	return 0
}

func (x *Date) GetDay() int32 {
	if x != nil && x.Day != nil {
		return *x.Day
	}
	return 0
}

type RenderEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (x *RenderEventRequest) Reset() {
	*x = RenderEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderEventRequest) ProtoMessage() {}

func (x *RenderEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderEventRequest.ProtoReflect.Descriptor instead.
func (*RenderEventRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *RenderEventRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type RenderEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date                *Date                                     `protobuf:"bytes,5,opt,name=date" json:"date,omitempty"`
	CompressedSnapshots []*RenderEventResponse_CompressedSnapshot `protobuf:"bytes,6,rep,name=compressed_snapshots,json=compressedSnapshots" json:"compressed_snapshots,omitempty"`
	PlaceStatsTotal     *RenderEventResponse_PlaceNoteCountStats  `protobuf:"bytes,3,opt,name=place_stats_total,json=placeStatsTotal" json:"place_stats_total,omitempty"`
	PlaceStatsFinished  *RenderEventResponse_PlaceNoteCountStats  `protobuf:"bytes,4,opt,name=place_stats_finished,json=placeStatsFinished" json:"place_stats_finished,omitempty"`
}

func (x *RenderEventResponse) Reset() {
	*x = RenderEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderEventResponse) ProtoMessage() {}

func (x *RenderEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderEventResponse.ProtoReflect.Descriptor instead.
func (*RenderEventResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *RenderEventResponse) GetDate() *Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *RenderEventResponse) GetCompressedSnapshots() []*RenderEventResponse_CompressedSnapshot {
	if x != nil {
		return x.CompressedSnapshots
	}
	return nil
}

func (x *RenderEventResponse) GetPlaceStatsTotal() *RenderEventResponse_PlaceNoteCountStats {
	if x != nil {
		return x.PlaceStatsTotal
	}
	return nil
}

func (x *RenderEventResponse) GetPlaceStatsFinished() *RenderEventResponse_PlaceNoteCountStats {
	if x != nil {
		return x.PlaceStatsFinished
	}
	return nil
}

type RenderPlaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (x *RenderPlaceRequest) Reset() {
	*x = RenderPlaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderPlaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderPlaceRequest) ProtoMessage() {}

func (x *RenderPlaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderPlaceRequest.ProtoReflect.Descriptor instead.
func (*RenderPlaceRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *RenderPlaceRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type RenderPlaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnownEventCount *int32 `protobuf:"varint,1,opt,name=known_event_count,json=knownEventCount" json:"known_event_count,omitempty"`
}

func (x *RenderPlaceResponse) Reset() {
	*x = RenderPlaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderPlaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderPlaceResponse) ProtoMessage() {}

func (x *RenderPlaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderPlaceResponse.ProtoReflect.Descriptor instead.
func (*RenderPlaceResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *RenderPlaceResponse) GetKnownEventCount() int32 {
	if x != nil && x.KnownEventCount != nil {
		return *x.KnownEventCount
	}
	return 0
}

type RenderActorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []string `protobuf:"bytes,1,rep,name=id" json:"id,omitempty"`
}

func (x *RenderActorsRequest) Reset() {
	*x = RenderActorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderActorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderActorsRequest) ProtoMessage() {}

func (x *RenderActorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderActorsRequest.ProtoReflect.Descriptor instead.
func (*RenderActorsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *RenderActorsRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type RenderActorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items map[string]*RenderActorsResponse_ResponseItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *RenderActorsResponse) Reset() {
	*x = RenderActorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderActorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderActorsResponse) ProtoMessage() {}

func (x *RenderActorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderActorsResponse.ProtoReflect.Descriptor instead.
func (*RenderActorsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *RenderActorsResponse) GetItems() map[string]*RenderActorsResponse_ResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type QueryEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset *int32                          `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Filter *QueryEventsRequest_EventFilter `protobuf:"bytes,4,opt,name=filter" json:"filter,omitempty"`
}

func (x *QueryEventsRequest) Reset() {
	*x = QueryEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsRequest) ProtoMessage() {}

func (x *QueryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryEventsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *QueryEventsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *QueryEventsRequest) GetFilter() *QueryEventsRequest_EventFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type QueryEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*QueryEventsResponse_Event `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
}

func (x *QueryEventsResponse) Reset() {
	*x = QueryEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsResponse) ProtoMessage() {}

func (x *QueryEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryEventsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *QueryEventsResponse) GetEvents() []*QueryEventsResponse_Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type RenderEventResponse_CompressedSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamps    []*timestamppb.Timestamp `protobuf:"bytes,1,rep,name=timestamps" json:"timestamps,omitempty"`
	NoteCount     *int32                   `protobuf:"varint,2,opt,name=note_count,json=noteCount" json:"note_count,omitempty"`
	AddedActors   []string                 `protobuf:"bytes,3,rep,name=added_actors,json=addedActors" json:"added_actors,omitempty"`
	RemovedActors []string                 `protobuf:"bytes,4,rep,name=removed_actors,json=removedActors" json:"removed_actors,omitempty"`
}

func (x *RenderEventResponse_CompressedSnapshot) Reset() {
	*x = RenderEventResponse_CompressedSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderEventResponse_CompressedSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderEventResponse_CompressedSnapshot) ProtoMessage() {}

func (x *RenderEventResponse_CompressedSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderEventResponse_CompressedSnapshot.ProtoReflect.Descriptor instead.
func (*RenderEventResponse_CompressedSnapshot) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RenderEventResponse_CompressedSnapshot) GetTimestamps() []*timestamppb.Timestamp {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *RenderEventResponse_CompressedSnapshot) GetNoteCount() int32 {
	if x != nil && x.NoteCount != nil {
		return *x.NoteCount
	}
	return 0
}

func (x *RenderEventResponse_CompressedSnapshot) GetAddedActors() []string {
	if x != nil {
		return x.AddedActors
	}
	return nil
}

func (x *RenderEventResponse_CompressedSnapshot) GetRemovedActors() []string {
	if x != nil {
		return x.RemovedActors
	}
	return nil
}

type RenderEventResponse_PlaceNoteCountStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total *int32 `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Rank  *int32 `protobuf:"varint,2,opt,name=rank" json:"rank,omitempty"`
}

func (x *RenderEventResponse_PlaceNoteCountStats) Reset() {
	*x = RenderEventResponse_PlaceNoteCountStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderEventResponse_PlaceNoteCountStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderEventResponse_PlaceNoteCountStats) ProtoMessage() {}

func (x *RenderEventResponse_PlaceNoteCountStats) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderEventResponse_PlaceNoteCountStats.ProtoReflect.Descriptor instead.
func (*RenderEventResponse_PlaceNoteCountStats) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2, 1}
}

func (x *RenderEventResponse_PlaceNoteCountStats) GetTotal() int32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *RenderEventResponse_PlaceNoteCountStats) GetRank() int32 {
	if x != nil && x.Rank != nil {
		return *x.Rank
	}
	return 0
}

type RenderActorsResponse_ResponseItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnownEventCount *int32                                        `protobuf:"varint,1,opt,name=known_event_count,json=knownEventCount" json:"known_event_count,omitempty"`
	Snapshots       []*RenderActorsResponse_ResponseItem_Snapshot `protobuf:"bytes,2,rep,name=snapshots" json:"snapshots,omitempty"`
}

func (x *RenderActorsResponse_ResponseItem) Reset() {
	*x = RenderActorsResponse_ResponseItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderActorsResponse_ResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderActorsResponse_ResponseItem) ProtoMessage() {}

func (x *RenderActorsResponse_ResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderActorsResponse_ResponseItem.ProtoReflect.Descriptor instead.
func (*RenderActorsResponse_ResponseItem) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6, 0}
}

func (x *RenderActorsResponse_ResponseItem) GetKnownEventCount() int32 {
	if x != nil && x.KnownEventCount != nil {
		return *x.KnownEventCount
	}
	return 0
}

func (x *RenderActorsResponse_ResponseItem) GetSnapshots() []*RenderActorsResponse_ResponseItem_Snapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type RenderActorsResponse_ResponseItem_Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date          *Date  `protobuf:"bytes,3,opt,name=date" json:"date,omitempty"`
	FavoriteCount *int32 `protobuf:"varint,2,opt,name=favorite_count,json=favoriteCount" json:"favorite_count,omitempty"`
}

func (x *RenderActorsResponse_ResponseItem_Snapshot) Reset() {
	*x = RenderActorsResponse_ResponseItem_Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderActorsResponse_ResponseItem_Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderActorsResponse_ResponseItem_Snapshot) ProtoMessage() {}

func (x *RenderActorsResponse_ResponseItem_Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderActorsResponse_ResponseItem_Snapshot.ProtoReflect.Descriptor instead.
func (*RenderActorsResponse_ResponseItem_Snapshot) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6, 0, 0}
}

func (x *RenderActorsResponse_ResponseItem_Snapshot) GetDate() *Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *RenderActorsResponse_ResponseItem_Snapshot) GetFavoriteCount() int32 {
	if x != nil && x.FavoriteCount != nil {
		return *x.FavoriteCount
	}
	return 0
}

type QueryEventsRequest_EventFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorIds []string `protobuf:"bytes,1,rep,name=actor_ids,json=actorIds" json:"actor_ids,omitempty"`
	PlaceId  *string  `protobuf:"bytes,2,opt,name=place_id,json=placeId" json:"place_id,omitempty"`
}

func (x *QueryEventsRequest_EventFilter) Reset() {
	*x = QueryEventsRequest_EventFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryEventsRequest_EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsRequest_EventFilter) ProtoMessage() {}

func (x *QueryEventsRequest_EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsRequest_EventFilter.ProtoReflect.Descriptor instead.
func (*QueryEventsRequest_EventFilter) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *QueryEventsRequest_EventFilter) GetActorIds() []string {
	if x != nil {
		return x.ActorIds
	}
	return nil
}

func (x *QueryEventsRequest_EventFilter) GetPlaceId() string {
	if x != nil && x.PlaceId != nil {
		return *x.PlaceId
	}
	return ""
}

type QueryEventsResponse_Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name          *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Date          *Date   `protobuf:"bytes,6,opt,name=date" json:"date,omitempty"`
	LastNoteCount *int32  `protobuf:"varint,5,opt,name=last_note_count,json=lastNoteCount" json:"last_note_count,omitempty"`
}

func (x *QueryEventsResponse_Event) Reset() {
	*x = QueryEventsResponse_Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryEventsResponse_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsResponse_Event) ProtoMessage() {}

func (x *QueryEventsResponse_Event) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsResponse_Event.ProtoReflect.Descriptor instead.
func (*QueryEventsResponse_Event) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8, 0}
}

func (x *QueryEventsResponse_Event) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *QueryEventsResponse_Event) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *QueryEventsResponse_Event) GetDate() *Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *QueryEventsResponse_Event) GetLastNoteCount() int32 {
	if x != nil && x.LastNoteCount != nil {
		return *x.LastNoteCount
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x74, 0x72, 0x65, 0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x62, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x42, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e,
	0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x64, 0x61, 0x79, 0x22, 0x24, 0x0a, 0x12, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x83, 0x05, 0x0a, 0x13, 0x52,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x69, 0x0a, 0x14,
	0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x74, 0x72, 0x65,
	0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x52, 0x13, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x12, 0x63, 0x0a, 0x11, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x37, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4e, 0x6f, 0x74,
	0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x0f, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x69, 0x0a, 0x14,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x66, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x74, 0x72, 0x65,
	0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x12, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x1a, 0xb9, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x3a,
	0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f,
	0x74, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x6e, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x64, 0x64,
	0x65, 0x64, 0x5f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0b, 0x61, 0x64, 0x64, 0x65, 0x64, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x41, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x1a, 0x3f, 0x0a, 0x13, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4e, 0x6f, 0x74, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x72, 0x61, 0x6e, 0x6b, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03,
	0x22, 0x24, 0x0a, 0x12, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x13, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x11, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x25, 0x0a, 0x13, 0x52, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0xc4, 0x03, 0x0a, 0x14, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x64,
	0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x1a, 0xf7, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x2a, 0x0a, 0x11, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x58, 0x0a,
	0x09, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x3a, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x09, 0x73, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x1a, 0x61, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x1a, 0x6b, 0x0a, 0x0a, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x47, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x74, 0x72, 0x65, 0x65,
	0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xbb, 0x01, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x46, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x64, 0x69, 0x61,
	0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x45,
	0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x0a,
	0x09, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0xe4, 0x01, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x74, 0x72, 0x65, 0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x1a, 0x89, 0x01, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74,
	0x72, 0x65, 0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61,
	0x74, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x4a, 0x04, 0x08, 0x03, 0x10, 0x04, 0x4a, 0x04, 0x08, 0x04, 0x10, 0x05, 0x32, 0xff, 0x02, 0x0a,
	0x12, 0x54, 0x72, 0x65, 0x65, 0x44, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x0b, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x22, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x64, 0x69, 0x61,
	0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a,
	0x0b, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x22, 0x2e, 0x74,
	0x72, 0x65, 0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x0c, 0x52, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x23, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x64, 0x69,
	0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x41,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x74,
	0x72, 0x65, 0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x22, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x64, 0x69, 0x61, 0x67, 0x72, 0x61,
	0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x74, 0x72, 0x65, 0x65, 0x64, 0x69,
	0x61, 0x67, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x25,
	0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x53, 0x48,
	0x5a, 0x2d, 0x4f, 0x52, 0x47, 0x2f, 0x74, 0x72, 0x65, 0x65, 0x2d, 0x64, 0x69, 0x61, 0x67, 0x72,
	0x61, 0x6d, 0x2f, 0x70, 0x62,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_service_proto_goTypes = []interface{}{
	(*Date)(nil),                                    // 0: treediagram.pb.Date
	(*RenderEventRequest)(nil),                      // 1: treediagram.pb.RenderEventRequest
	(*RenderEventResponse)(nil),                     // 2: treediagram.pb.RenderEventResponse
	(*RenderPlaceRequest)(nil),                      // 3: treediagram.pb.RenderPlaceRequest
	(*RenderPlaceResponse)(nil),                     // 4: treediagram.pb.RenderPlaceResponse
	(*RenderActorsRequest)(nil),                     // 5: treediagram.pb.RenderActorsRequest
	(*RenderActorsResponse)(nil),                    // 6: treediagram.pb.RenderActorsResponse
	(*QueryEventsRequest)(nil),                      // 7: treediagram.pb.QueryEventsRequest
	(*QueryEventsResponse)(nil),                     // 8: treediagram.pb.QueryEventsResponse
	(*RenderEventResponse_CompressedSnapshot)(nil),  // 9: treediagram.pb.RenderEventResponse.CompressedSnapshot
	(*RenderEventResponse_PlaceNoteCountStats)(nil), // 10: treediagram.pb.RenderEventResponse.PlaceNoteCountStats
	(*RenderActorsResponse_ResponseItem)(nil),       // 11: treediagram.pb.RenderActorsResponse.ResponseItem
	nil, // 12: treediagram.pb.RenderActorsResponse.ItemsEntry
	(*RenderActorsResponse_ResponseItem_Snapshot)(nil), // 13: treediagram.pb.RenderActorsResponse.ResponseItem.Snapshot
	(*QueryEventsRequest_EventFilter)(nil),             // 14: treediagram.pb.QueryEventsRequest.EventFilter
	(*QueryEventsResponse_Event)(nil),                  // 15: treediagram.pb.QueryEventsResponse.Event
	(*timestamppb.Timestamp)(nil),                      // 16: google.protobuf.Timestamp
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: treediagram.pb.RenderEventResponse.date:type_name -> treediagram.pb.Date
	9,  // 1: treediagram.pb.RenderEventResponse.compressed_snapshots:type_name -> treediagram.pb.RenderEventResponse.CompressedSnapshot
	10, // 2: treediagram.pb.RenderEventResponse.place_stats_total:type_name -> treediagram.pb.RenderEventResponse.PlaceNoteCountStats
	10, // 3: treediagram.pb.RenderEventResponse.place_stats_finished:type_name -> treediagram.pb.RenderEventResponse.PlaceNoteCountStats
	12, // 4: treediagram.pb.RenderActorsResponse.items:type_name -> treediagram.pb.RenderActorsResponse.ItemsEntry
	14, // 5: treediagram.pb.QueryEventsRequest.filter:type_name -> treediagram.pb.QueryEventsRequest.EventFilter
	15, // 6: treediagram.pb.QueryEventsResponse.events:type_name -> treediagram.pb.QueryEventsResponse.Event
	16, // 7: treediagram.pb.RenderEventResponse.CompressedSnapshot.timestamps:type_name -> google.protobuf.Timestamp
	13, // 8: treediagram.pb.RenderActorsResponse.ResponseItem.snapshots:type_name -> treediagram.pb.RenderActorsResponse.ResponseItem.Snapshot
	11, // 9: treediagram.pb.RenderActorsResponse.ItemsEntry.value:type_name -> treediagram.pb.RenderActorsResponse.ResponseItem
	0,  // 10: treediagram.pb.RenderActorsResponse.ResponseItem.Snapshot.date:type_name -> treediagram.pb.Date
	0,  // 11: treediagram.pb.QueryEventsResponse.Event.date:type_name -> treediagram.pb.Date
	1,  // 12: treediagram.pb.TreeDiagramService.RenderEvent:input_type -> treediagram.pb.RenderEventRequest
	3,  // 13: treediagram.pb.TreeDiagramService.RenderPlace:input_type -> treediagram.pb.RenderPlaceRequest
	5,  // 14: treediagram.pb.TreeDiagramService.RenderActors:input_type -> treediagram.pb.RenderActorsRequest
	7,  // 15: treediagram.pb.TreeDiagramService.QueryEvents:input_type -> treediagram.pb.QueryEventsRequest
	2,  // 16: treediagram.pb.TreeDiagramService.RenderEvent:output_type -> treediagram.pb.RenderEventResponse
	4,  // 17: treediagram.pb.TreeDiagramService.RenderPlace:output_type -> treediagram.pb.RenderPlaceResponse
	6,  // 18: treediagram.pb.TreeDiagramService.RenderActors:output_type -> treediagram.pb.RenderActorsResponse
	8,  // 19: treediagram.pb.TreeDiagramService.QueryEvents:output_type -> treediagram.pb.QueryEventsResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Date); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderPlaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderPlaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderActorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderActorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderEventResponse_CompressedSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderEventResponse_PlaceNoteCountStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderActorsResponse_ResponseItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderActorsResponse_ResponseItem_Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryEventsRequest_EventFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryEventsResponse_Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
